<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <NoWarn>CS8632</NoWarn> <!-- Suppress this specific warning -->

    <RootNamespace>Alexapps.SkinCare</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Alexapps.SkinCare.EntityFrameworkCore\Alexapps.SkinCare.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Alexapps.SkinCare.Application.Tests\Alexapps.SkinCare.Application.Tests.csproj" />
    <PackageReference Include="Hangfire" Version="1.8.24" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1.0" />
  </ItemGroup>

</Project>


